### ISSUE TITLE
Run Test cancels without any error

### ISSUE THREAD

**Issue by Peacemaler** [WidgetsBurritos/webpagetest#10]
Following Code always run into "exit(2)" 
$response is NULL.

$wpt = new WebPageTest($key);
        $options = [
            'location' => 'Falkenstein:Chrome.Cable',
            'priority' => 1,
            'video' => 1,
            'mobile' => 0,
];

if ($response = $wpt->runTest($website->getUrl(), $options)) {
                  
                    if ($response->statusCode == 200) {
                        .....
                    } else if ($response->statusCode == 100) {
                        ......
                    } else if ($response->statusCode == 400) {
                        .....
                    } else {
                        .........
                    }
  }else{
        exit(2);
}

**Comment by WidgetsBurritos** [comment]
What is the value of `$website->getUrl()`? 

I just ran this code on `https://www.google.com` and it seems to have worked without any issues.

**Comment by WidgetsBurritos** [comment]
Closing this issue as it's been 2 months without a response.  If you are still having issues, please feel free to reopen this issue.
