### ISSUE TITLE
'Cancelling Tests' feature

### ISSUE THREAD

**Issue by dimonx3** [WidgetsBurritos/webpagetest#11]
WebPagetest RESTful APIs has feature 'Cancelling Tests'. Please add this feature to your library.
https://sites.google.com/a/webpagetest.org/docs/advanced-features/webpagetest-restful-apis#TOC-Cancelling-Tests

**Comment by WidgetsBurritos** [comment]
Sorry for the delayed response. I somehow missed the notification for this issue.  I'll look into adding it. 

This shouldn't be too complicated to add, but I'm not entirely sure from the documentation what WPT returns when cancelling a test, so I'll need to find some time to look into that.

**Comment by WidgetsBurritos** [comment]
@dimonx3 

Thank you for the feature request. It has been added as of v1.0.4.

To cancel a test run: 
```php
$wpt->cancelTest($test_id);
```

To confirm a test has been cancelled:
```php
if ($response = $wpt->getTestStatus($test_id)) {
  if ($response->statusCode == StatusCode::PAYMENT_REQUIRED) {
    // Test has been cancelled.
  }
}
```

^ Note: This is not a mistake. WPT uses the "402 Payment Required" status to indicate that a test has been cancelled.

**Comment by dimonx3** [comment]
Thank you very much
